title: zera.holladay
email: zeraholladay@gmail.com
description: >
    Python and Java Coding
    Microservices
    Devops 
    Cooking Recipies
baseurl: ""
url: "https://zeraholladay.github.io" # the base hostname & protocol for your site
twitter_username: zeraholladay
github_username:  zeraholladay

# Build settings
markdown: kramdown
theme: minima
